### PR TITLE
Use executeBlocking to call the next service

### PR DESCRIPTION
**Pull request by cescoffier**
As discussed in #1, here is the second PR.

### CODE REVIEW

**Comment by rafabene** [comment]
Well, this code seems much more legible than the version on #1 . I propose that we merge this version instead  #1. Any objections @yanaga and @christian-posta ?

**Comment by christian-posta** [comment]
Yah agreed @rafabene 
+1 to this PR

**Comment by yanaga** [comment]
If that's the Vert.x way, then I presume it's the most readable and understandable option within the constraints. +1

**Comment by cescoffier** [comment]
This way is definitely closer to the vert.x way and it perfectly fine for vert.x. The "pure" vert.x way would be to use a non-blocking HTTP client, but unfortunately, Feign does not support this. It has an async version, but the callback is called in their own thread pool (and not the event loop) and it requires to switch to RX (which in this case it not useful, and confusing).

You may wonder why being called in the event loop is important. This is because Vert.x components are (generally, as there is rare exceptions) called by a single thread, so you don't need synchronization. As we never blocks this thread, it can handle a huge load. Not being executed by the right thread, breaks this, so you would need synchronization...

**Comment by rafabene** [comment]
Thanks for the explanation @cescoffier . So I just merged this version and closed #1 . Thanks for the comments and votes @christian-posta @yanaga

**Comment by cescoffier** [comment]
:+1:

**Pull request merged**
